### ISSUE TITLE
Add brew tap `homebrew/cask-fonts` support

### ISSUE THREAD

**Issue by yeskunall** [intel/intel-one-mono#26]
See: https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md

**Comment by TobiasFrereJones** [comment]
Thanks for the suggestion! It looks like homebrew-cask-fonts automatically incorporates fonts once they are added to Google Fonts. Intel One Mono is currently in the process of being added to Google Fonts, so we expect this issue to resolve itself. Since there is no additional action for us to take, we’ll close the issue.
