### ISSUE TITLE
Incorrect Display of Button Names on Google Bard Website in Mozilla Firefox (116.0/64-bit) on Windows 11

### ISSUE THREAD

**Issue by OsirisLogos** [intel/intel-one-mono#45]
![IntelOne Mono on Google Bard](https://github.com/intel/intel-one-mono/assets/111147137/2c17b4c0-9271-4ab6-97c0-b4f6448e01d0)

When visiting the Google Bard website using the Mozilla Firefox browser (version 116.0, 64-bit) on Windows 11, I've noticed an issue with the IntelOne Mono font. Instead of correctly displaying button names, they appear as random characters. This problem seems to only occur on this specific website, and I have not noticed this issue on any other websites.

**Comment by ninastoessinger** [comment]
Thanks for trying this out and reporting back. It looks like the buttons/icons on that page are usually rendered by means of a specific icon font; if this gets replaced with Intel One Mono, the fallback text is shown (or however much of the fallback text fits into the available space), since Intel One Mono does not contain those exact icons. If you can find a way to just replace the fonts used for text on that page with Intel One Mono, rather than all fonts on the page, that might be a way to make it work.
